#!/usr/bin/env python3
"""lb_filter.py — emit a NestJS 12 + TypeORM module that understands the
LoopBack 3 `filter` query language.

LoopBack 3 exposes a rich REST query language through a single `filter` query
string, e.g.

    GET /coffeeShops?filter={"where":{"city":"NYC","rating":{"gte":4}},
                            "include":"reviews","order":"name ASC",
                            "limit":10,"skip":20,"fields":["id","name"]}

When a LoopBack app is migrated to NestJS + TypeORM, every existing API client
that builds these `filter` objects breaks unless the new app speaks the same
syntax. This script GENERATES a small, reusable TypeScript module that does the
translation: a `LoopbackFilterPipe` (NestJS `PipeTransform`) plus a pure
`toFindManyOptions()` helper that parses a LoopBack `filter` (JSON string or an
already-parsed object) and returns a TypeORM `FindManyOptions`
(where / relations / order / take / skip / select).

The translation logic lives entirely in the emitted TypeScript; this Python
script only writes those `.ts` files (a generator, matching the repo's
Python/no-deps + emit-TypeScript convention, like `lb2nest.py`). Nothing here
runs Node.

Emitted files (into the output directory, flat):
  loopback-filter.types.ts      LoopBack filter type declarations
  loopback-filter.converter.ts  pure conversion logic + LoopbackFilterError
  loopback-filter.pipe.ts       the NestJS pipe wrapping the converter
  index.ts                      barrel re-export

Operator mapping (LoopBack where -> TypeORM):
  gt->MoreThan  gte->MoreThanOrEqual  lt->LessThan  lte->LessThanOrEqual
  between->Between  inq->In  nin->Not(In(...))  neq->Not(...)
  like->Like  nlike->Not(Like(...))  ilike->ILike  nilike->Not(ILike(...))
  and->merged AND clause  or->array of where clauses (OR)
  regexp, near -> unsupported (the emitted code throws LoopbackFilterError)

Python 3.9+, no dependencies.

Usage:
  ./lb_filter.py                       # write module into ./loopback-filter
  ./lb_filter.py -o src/common/lb      # choose the output directory
  ./lb_filter.py --dry-run             # list files, write nothing
  ./lb_filter.py --force               # overwrite a non-empty output dir
  ./lb_filter.py --stdout              # print all files to stdout, write nothing

Options:
  -o, --out DIR   output directory (default: ./loopback-filter)
  --force         overwrite an existing non-empty output directory
  --dry-run       list the files that would be written, write nothing
  --stdout        concatenate the files to stdout (implies no writes)

Exit codes: 0 ok, 1 refusing to overwrite / bad args.
"""

import argparse
import os
import sys


class GeneratorError(Exception):
    pass


# ---------------------------------------------------------------------------
# The LoopBack where operator -> TypeORM mapping, as data. The emitted
# TypeScript encodes the same table; this copy documents it and lets the tests
# assert the emitter stayed in sync.
# ---------------------------------------------------------------------------

OPERATOR_MAP = {
    "gt": "MoreThan",
    "gte": "MoreThanOrEqual",
    "lt": "LessThan",
    "lte": "LessThanOrEqual",
    "between": "Between",
    "inq": "In",
    "nin": "Not(In(...))",
    "neq": "Not(...)",
    "like": "Like",
    "nlike": "Not(Like(...))",
    "ilike": "ILike",
    "nilike": "Not(ILike(...))",
    "and": "merged AND clause (same field -> And())",
    "or": "array of where clauses (OR)",
}

UNSUPPORTED_OPERATORS = {
    "regexp": "no portable TypeORM FindOptions equivalent; use QueryBuilder + raw SQL",
    "near": "geospatial; issue a spatial query via QueryBuilder",
}


# ---------------------------------------------------------------------------
# Emitters — each returns a complete .ts file as a string. Plain (non-f)
# strings so the TypeScript braces need no escaping.
# ---------------------------------------------------------------------------


def gen_types():
    return """/**
 * loopback-filter.types.ts — Types describing a LoopBack 3 `filter` object.
 * Generated by lb_filter.py (ai-scripts/lb-filter). Types only, zero runtime.
 */

export type LoopbackOrder = string | string[];

export type LoopbackInclude =
  | string
  | Array<string | Record<string, unknown>>
  | Record<string, unknown>;

export interface LoopbackFilter {
  where?: Record<string, unknown>;
  include?: LoopbackInclude;
  order?: LoopbackOrder;
  limit?: number;
  skip?: number;
  offset?: number;
  fields?: string[] | Record<string, boolean>;
}
"""


def gen_converter():
    return """/**
 * loopback-filter.converter.ts — Convert a LoopBack 3 `filter` object into a
 * TypeORM FindManyOptions. Generated by lb_filter.py (ai-scripts/lb-filter).
 *
 * Pure functions, no NestJS dependency, so this is unit-testable on its own;
 * LoopbackFilterPipe simply wraps `toFindManyOptions` for use in controllers.
 *
 * Operator mapping (LoopBack where -> TypeORM):
 *   gt    -> MoreThan            gte    -> MoreThanOrEqual
 *   lt    -> LessThan            lte    -> LessThanOrEqual
 *   between -> Between           inq    -> In
 *   nin   -> Not(In(...))        neq    -> Not(...)
 *   like  -> Like                nlike  -> Not(Like(...))
 *   ilike -> ILike               nilike -> Not(ILike(...))
 *   and   -> merged AND clause   or     -> array of where clauses (OR)
 *   regexp, near -> unsupported (throws LoopbackFilterError)
 *
 * Notes:
 *   - Multiple operators on one field (e.g. { gt: 5, lt: 10 }) and repeated
 *     conditions on one field across an `and` are combined with TypeORM's
 *     And() combinator, which requires typeorm >= 0.3.17.
 *   - A `where` with `or` is emitted as a TypeORM `where` ARRAY (array = OR);
 *     nested and/or is flattened to disjunctive normal form.
 *   - `like` honours a sibling { options: 'i' } by switching to ILike.
 */

import {
  And,
  Between,
  Equal,
  FindManyOptions,
  FindOperator,
  FindOptionsOrder,
  FindOptionsWhere,
  ILike,
  In,
  IsNull,
  LessThan,
  LessThanOrEqual,
  Like,
  MoreThan,
  MoreThanOrEqual,
  Not,
} from 'typeorm';
import { LoopbackFilter, LoopbackInclude } from './loopback-filter.types';

export class LoopbackFilterError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'LoopbackFilterError';
  }
}

/** where operators we understand. `options` is a sibling flag, not an operator. */
const KNOWN_OPERATORS = new Set([
  'gt', 'gte', 'lt', 'lte', 'between', 'inq', 'nin', 'neq',
  'like', 'nlike', 'ilike', 'nilike', 'regexp', 'near',
]);

function asOperator(value: unknown): FindOperator<any> {
  return value instanceof FindOperator ? value : Equal(value as any);
}

function buildOperator(
  op: string,
  arg: unknown,
  caseInsensitive: boolean,
): FindOperator<any> {
  switch (op) {
    case 'gt':
      return MoreThan(arg as any);
    case 'gte':
      return MoreThanOrEqual(arg as any);
    case 'lt':
      return LessThan(arg as any);
    case 'lte':
      return LessThanOrEqual(arg as any);
    case 'between':
      if (!Array.isArray(arg) || arg.length !== 2) {
        throw new LoopbackFilterError(
          "'between' expects a two-element array [from, to].",
        );
      }
      return Between(arg[0], arg[1]);
    case 'inq':
      if (!Array.isArray(arg)) {
        throw new LoopbackFilterError("'inq' expects an array of values.");
      }
      return In(arg);
    case 'nin':
      if (!Array.isArray(arg)) {
        throw new LoopbackFilterError("'nin' expects an array of values.");
      }
      return Not(In(arg));
    case 'neq':
      return arg === null ? Not(IsNull()) : Not(arg as any);
    case 'like':
      return caseInsensitive ? ILike(arg as string) : Like(arg as string);
    case 'nlike':
      return Not(caseInsensitive ? ILike(arg as string) : Like(arg as string));
    case 'ilike':
      return ILike(arg as string);
    case 'nilike':
      return Not(ILike(arg as string));
    case 'regexp':
      throw new LoopbackFilterError(
        "The 'regexp' operator has no portable TypeORM FindOptions equivalent; " +
          'use a QueryBuilder with a raw WHERE clause instead.',
      );
    case 'near':
      throw new LoopbackFilterError(
        "The 'near' geospatial operator is not supported; " +
          'issue a spatial query via QueryBuilder.',
      );
    default:
      throw new LoopbackFilterError(`Unknown LoopBack operator '${op}'.`);
  }
}

/** Convert one field's condition: a primitive (equals) or an operator object. */
function convertCondition(value: unknown): unknown {
  if (value === null) {
    return IsNull();
  }
  if (typeof value !== 'object' || Array.isArray(value) || value instanceof Date) {
    return value; // primitive (or array / date) -> equality
  }
  const cond = value as Record<string, unknown>;
  const caseInsensitive = cond.options === 'i';
  const ops = Object.keys(cond).filter((k) => k !== 'options');
  if (ops.length === 0) {
    return value; // an empty object -> treat as a literal
  }
  for (const op of ops) {
    if (!KNOWN_OPERATORS.has(op)) {
      throw new LoopbackFilterError(
        `Unknown LoopBack operator '${op}' on a where condition.`,
      );
    }
  }
  const operators = ops.map((op) => buildOperator(op, cond[op], caseInsensitive));
  return operators.length === 1 ? operators[0] : And(...operators);
}

/** Merge two AND clauses; a field present in both is combined with And(). */
function mergeClause(
  a: FindOptionsWhere<any>,
  b: FindOptionsWhere<any>,
): FindOptionsWhere<any> {
  const out: Record<string, any> = { ...a };
  for (const [key, value] of Object.entries(b)) {
    if (key in out) {
      out[key] = And(asOperator(out[key]), asOperator(value));
    } else {
      out[key] = value;
    }
  }
  return out;
}

function andCombine(
  left: FindOptionsWhere<any>[],
  right: FindOptionsWhere<any>[],
): FindOptionsWhere<any>[] {
  const out: FindOptionsWhere<any>[] = [];
  for (const a of left) {
    for (const b of right) {
      out.push(mergeClause(a, b));
    }
  }
  return out;
}

/**
 * Flatten a LoopBack `where` into disjunctive normal form: an array of AND
 * clauses. The array itself is the OR — TypeORM reads a `where` array as OR.
 */
function whereToClauses(where: unknown): FindOptionsWhere<any>[] {
  if (where === null || typeof where !== 'object') {
    return [{}];
  }
  const parts: FindOptionsWhere<any>[][] = [];
  const fieldClause: Record<string, any> = {};
  let hasField = false;

  for (const [key, value] of Object.entries(where as Record<string, unknown>)) {
    if (key === 'and') {
      if (!Array.isArray(value)) {
        throw new LoopbackFilterError("'and' expects an array of conditions.");
      }
      for (const sub of value) {
        parts.push(whereToClauses(sub));
      }
    } else if (key === 'or') {
      if (!Array.isArray(value)) {
        throw new LoopbackFilterError("'or' expects an array of conditions.");
      }
      const branches: FindOptionsWhere<any>[] = [];
      for (const sub of value) {
        branches.push(...whereToClauses(sub));
      }
      parts.push(branches);
    } else {
      fieldClause[key] = convertCondition(value);
      hasField = true;
    }
  }

  if (hasField) {
    parts.unshift([fieldClause]);
  }
  if (parts.length === 0) {
    return [{}];
  }
  return parts.reduce(andCombine, [{}] as FindOptionsWhere<any>[]);
}

/** LoopBack `order` ("prop ASC" / ["a ASC", "b DESC"]) -> TypeORM order object. */
function convertOrder(order: string | string[]): FindOptionsOrder<any> {
  const clauses = Array.isArray(order) ? order : [order];
  const out: Record<string, 'ASC' | 'DESC'> = {};
  for (const clause of clauses) {
    const [prop, dir] = String(clause).trim().split(/\\s+/);
    if (!prop) {
      continue;
    }
    out[prop] = (dir || 'ASC').toUpperCase() === 'DESC' ? 'DESC' : 'ASC';
  }
  return out as FindOptionsOrder<any>;
}

/**
 * LoopBack `include` -> TypeORM `relations` (dot-notation string list).
 * Only the relation graph carries over; include `scope` filters (where/limit
 * on an included relation) have no FindOptions equivalent and are dropped.
 */
function collectRelations(include: LoopbackInclude, prefix = ''): string[] {
  const out: string[] = [];
  const join = (rel: string) => (prefix ? `${prefix}.${rel}` : rel);

  if (typeof include === 'string') {
    out.push(join(include));
  } else if (Array.isArray(include)) {
    for (const item of include) {
      out.push(...collectRelations(item as LoopbackInclude, prefix));
    }
  } else if (include && typeof include === 'object') {
    const obj = include as Record<string, unknown>;
    if (typeof obj.relation === 'string') {
      const path = join(obj.relation);
      out.push(path);
      const scope = obj.scope as Record<string, unknown> | undefined;
      if (scope && scope.include) {
        out.push(...collectRelations(scope.include as LoopbackInclude, path));
      }
    } else {
      for (const [rel, value] of Object.entries(obj)) {
        const path = join(rel);
        out.push(path);
        if (value && value !== true) {
          out.push(...collectRelations(value as LoopbackInclude, path));
        }
      }
    }
  }
  return Array.from(new Set(out));
}

/** LoopBack `fields` -> TypeORM `select` (an allow-list). */
function convertFields(fields: string[] | Record<string, boolean>): string[] {
  if (Array.isArray(fields)) {
    return fields.slice();
  }
  if (fields && typeof fields === 'object') {
    const include: string[] = [];
    const exclude: string[] = [];
    for (const [key, value] of Object.entries(fields)) {
      (value ? include : exclude).push(key);
    }
    if (exclude.length > 0) {
      throw new LoopbackFilterError(
        'Exclusive `fields` ({ prop: false }) select the complement of columns, ' +
          'which a TypeORM FindOptions `select` (an allow-list) cannot express. ' +
          'List the fields to keep instead.',
      );
    }
    return include;
  }
  throw new LoopbackFilterError('`fields` must be an array or an object.');
}

/**
 * Convert a LoopBack 3 `filter` (JSON string or parsed object) into a TypeORM
 * FindManyOptions. Throws LoopbackFilterError on unsupported constructs.
 */
export function toFindManyOptions<T = any>(
  filter: string | LoopbackFilter | null | undefined,
): FindManyOptions<T> {
  if (filter === null || filter === undefined || filter === '') {
    return {};
  }

  let parsed: LoopbackFilter;
  if (typeof filter === 'string') {
    try {
      parsed = JSON.parse(filter) as LoopbackFilter;
    } catch (err) {
      throw new LoopbackFilterError(
        `filter is not valid JSON: ${(err as Error).message}`,
      );
    }
  } else {
    parsed = filter;
  }

  const options: FindManyOptions<T> = {};

  if (parsed.where !== undefined) {
    const clauses = whereToClauses(parsed.where);
    options.where = (clauses.length === 1 ? clauses[0] : clauses) as
      | FindOptionsWhere<T>
      | FindOptionsWhere<T>[];
  }
  if (parsed.include !== undefined) {
    const relations = collectRelations(parsed.include);
    if (relations.length > 0) {
      options.relations = relations;
    }
  }
  if (parsed.order !== undefined) {
    options.order = convertOrder(parsed.order) as FindOptionsOrder<T>;
  }
  if (parsed.limit !== undefined) {
    options.take = Number(parsed.limit);
  }
  if (parsed.skip !== undefined || parsed.offset !== undefined) {
    options.skip = Number(parsed.skip ?? parsed.offset);
  }
  if (parsed.fields !== undefined) {
    options.select = convertFields(
      parsed.fields,
    ) as unknown as FindManyOptions<T>['select'];
  }

  return options;
}
"""


def gen_pipe():
    return """/**
 * loopback-filter.pipe.ts — NestJS pipe that turns a LoopBack 3 `filter` query
 * param into a TypeORM FindManyOptions. Generated by lb_filter.py.
 *
 * Usage:
 *   @Get()
 *   findAll(
 *     @Query('filter', LoopbackFilterPipe) options: FindManyOptions<CoffeeShop>,
 *   ) {
 *     return this.repo.find(options);
 *   }
 *
 * An invalid filter (bad JSON or an unsupported construct) becomes a
 * 400 Bad Request via BadRequestException.
 */

import {
  ArgumentMetadata,
  BadRequestException,
  Injectable,
  PipeTransform,
} from '@nestjs/common';
import { FindManyOptions } from 'typeorm';
import { LoopbackFilter } from './loopback-filter.types';
import {
  LoopbackFilterError,
  toFindManyOptions,
} from './loopback-filter.converter';

@Injectable()
export class LoopbackFilterPipe<T = any>
  implements
    PipeTransform<string | LoopbackFilter | undefined, FindManyOptions<T>>
{
  transform(
    value: string | LoopbackFilter | undefined,
    _metadata?: ArgumentMetadata,
  ): FindManyOptions<T> {
    try {
      return toFindManyOptions<T>(value);
    } catch (err) {
      if (err instanceof LoopbackFilterError) {
        throw new BadRequestException(err.message);
      }
      throw err;
    }
  }
}
"""


def gen_index():
    return """/**
 * index.ts — barrel for the generated LoopBack filter module.
 * Generated by lb_filter.py (ai-scripts/lb-filter).
 */

export * from './loopback-filter.types';
export * from './loopback-filter.converter';
export * from './loopback-filter.pipe';
"""


# ---------------------------------------------------------------------------
# Assemble + write
# ---------------------------------------------------------------------------


def build_files():
    """Return {relpath: content} for the whole emitted module."""
    return {
        "loopback-filter.types.ts": gen_types(),
        "loopback-filter.converter.ts": gen_converter(),
        "loopback-filter.pipe.ts": gen_pipe(),
        "index.ts": gen_index(),
    }


def write_files(files, out_dir, force, dry_run):
    if os.path.isdir(out_dir) and os.listdir(out_dir) and not force and not dry_run:
        raise GeneratorError(
            f"output directory {out_dir} is not empty; pass --force to overwrite")
    written = []
    for rel, content in sorted(files.items()):
        dest = os.path.join(out_dir, rel)
        written.append(dest)
        if dry_run:
            continue
        os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
        with open(dest, "w", encoding="utf-8") as fh:
            fh.write(content)
    return written


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="lb_filter.py",
        description="Emit a NestJS 12 + TypeORM module implementing a "
                    "LoopBack 3 `filter` -> FindManyOptions pipe.")
    parser.add_argument("-o", "--out", default="./loopback-filter",
                        help="output directory (default: ./loopback-filter)")
    parser.add_argument("--force", action="store_true",
                        help="overwrite a non-empty output directory")
    parser.add_argument("--dry-run", action="store_true",
                        help="list files, write nothing")
    parser.add_argument("--stdout", action="store_true",
                        help="print all files to stdout, write nothing")

    args = parser.parse_args(argv)
    files = build_files()

    if args.stdout:
        for rel, content in sorted(files.items()):
            print(f"// ==== {rel} ====")
            print(content)
        return 0

    try:
        written = write_files(files, args.out, args.force, args.dry_run)
    except GeneratorError as exc:
        print(f"lb_filter: {exc}", file=sys.stderr)
        return 1

    verb = "would write" if args.dry_run else "wrote"
    for w in written:
        print(f"{verb} {w}")
    print(f"\n{len(written)} files -> {args.out}", file=sys.stderr)
    if not args.dry_run:
        print("Next: import { LoopbackFilterPipe } and use "
              "@Query('filter', LoopbackFilterPipe) in a controller. "
              "Requires typeorm >= 0.3.17.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
